# Generated by Django 4.0.4 on 2022-05-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helloworld',
            old_name='text',
            new_name='text_test_0001init',
        ),
        migrations.AddField(
            model_name='helloworld',
            name='text_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
