# Generated by Django 4.0.4 on 2022-05-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_rename_text_helloworld_text_test_0001init_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helloworld',
            old_name='text_test_0001init',
            new_name='text_model_test',
        ),
        migrations.RemoveField(
            model_name='helloworld',
            name='text_2',
        ),
    ]
