# Generated by Django 4.0.4 on 2022-05-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_rename_text_test_0001init_helloworld_text_model_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helloworld',
            old_name='text_model_test',
            new_name='text',
        ),
    ]
